name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          if [[ ${{ matrix.goos }} == 'windows' ]]; then
            OUTPUT_NAME=helmup-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          else
            OUTPUT_NAME=helmup-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          fi
          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o $OUTPUT_NAME

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: helmup-*
