name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set up Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          if [[ ${{ matrix.goos }} == 'windows' ]]; then
            OUTPUT_NAME=helmup-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}.exe
          else
            OUTPUT_NAME=helmup-${{ github.event.release.tag_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          fi

          LD_FLAGS="-s -X 'helmup/cmd.Version=${{ github.event.release.tag_name }}' -X 'helmup/cmd.GitCommit=${GITHUB_SHA::10}'"

          env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="$LD_FLAGS" -v -o "$OUTPUT_NAME"

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: helmup-*

      - name: Generate PKGBUILD
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        run: |
          export VERSION="${{ github.event.release.tag_name }}"
          export SOURCE="helmup::https://github.com/rubengees/helmup/releases/download/$VERSION/helmup-$VERSION-linux-amd64"

          MD5SUMS=$(md5sum helmup-* | cut -f 1 -d " ")
          export MD5SUMS

          envsubst '$VERSION:$SOURCE:$MD5SUMS' <.github/PKGBUILD > PKGBUILD

      - name: Publish AUR package
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: helmup-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to ${{ github.event.release.tag_name }}
